---

- name: Install Dependancies
  package:
    name: "{{ librenms_agent_snmp_dependant_packages }}"
    state: present

- name: Creating snmp script folder
  file:
    path: "{{ librenms_agent_snmp_scripts_dir }}"
    state: directory
    mode: 0755
    group: root
    owner: root

- name: Install snmp Scripts
  get_url:
    url: "{{ librenms_agent_snmp_github_repo }}/{{ item }}"
    dest: "{{ librenms_agent_snmp_scripts_dir }}/{{ item }}"
    force: "{{ librenms_agent_scripts_update }}"
    mode: 0755
  failed_when: false
  with_flattened: "{{ librenms_agent_snmp_scripts }}"
  register: script_results

- name: Install snmp Scripts with .sh
  get_url:
    url: "{{ librenms_agent_snmp_github_repo }}/{{ item.item }}.sh"
    dest: "{{ librenms_agent_snmp_scripts_dir }}/{{ item.item }}"
    force: "{{ librenms_agent_scripts_update }}"
    mode: 0755
  with_items: "{{ script_results.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.status_code is defined and item.status_code == 404

- name: Disable snmp Logging
  replace:
    path: /lib/systemd/system/snmpd.service
    regexp: '(\s+)-Lsd(\s+.*)?$'
    replace: '\1-LSed\2'
  when: librenms_agent_snmp_no_logging
  notify: Reload snmpd

- name: Configure snmp
  template:
    src: "snmpd.conf.j2"
    dest: "{{ librenms_agent_snmp_dir }}/snmpd.conf"
    owner: root
    group: root
    mode: 0644
  notify: Restart snmpd
