---

- name: "Include {{ ansible_os_family }} Specific Variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "{{ ansible_os_family }} Fmaily"
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Install snmp
  include_tasks: _snmp.yml
  when: librenms_agent_snmp_scripts is defined and ( librenms_agent_snmp_scripts | length > 0 )

- name: Install check_mk
  include_tasks: _check_mk.yml
  when: (librenms_agent_check_mk_scripts is defined and ( librenms_agent_check_mk_scripts | length > 0 )) or librenms_agent_check_mk

- name: Configure Scripts
  include_tasks: scripts/main.yml
